version: 2.1

jobs:
  build:
    docker: 
      - image: cimg/base:current
    steps:
      - run: echo "Terraform Job is about to start"
  start:
    docker: 
      - image: cimg/base:current
    steps:
      - run: echo "Start project"
 
workflows:
  demo-workflows:
    jobs:
      - build